config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :institutions do
    resources :data_records, :tuitions, :faculty_headcounts, :inst_contacts
  end
  resources :regions do
    resources :regional_data_records
  end
  devise_for :principals, :controllers => { registrations: 'registrations' }
  root to: 'institutions#index'
  resources :sections
  resources :teachers
  resources :tesda_courses
  resources :tesda_course_sectors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_record.rb
class DataRecord < ApplicationRecord
  belongs_to :institution
end

app/models/faculty_headcount.rb
class FacultyHeadcount < ApplicationRecord
  belongs_to :institution
end

app/models/inst_contact.rb
class InstContact < ApplicationRecord
  belongs_to :institution
end

app/models/institution.rb
class Institution < ApplicationRecord
  belongs_to :region
  has_many :data_records, dependent: :delete_all
  has_many :faculty_headcounts, dependent: :delete_all
  has_many :tuitions, dependent: :delete_all
  has_many :inst_contacts, dependent: :delete_all
  has_and_belongs_to_many :tesda_courses
  has_many :sections, dependent: :delete_all
  has_many :teachers, dependent: :delete_all
  has_many :principals, dependent: :delete_all
end

app/models/principal.rb
class Principal < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :institution
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :regional_data_records, dependent: :delete_all
  has_many :institutions, dependent: :delete_all
end

app/models/regional_data_record.rb
class RegionalDataRecord < ApplicationRecord
  belongs_to :region
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :institution
  has_and_belongs_to_many :teachers
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :institution
  has_and_belongs_to_many :tesda_courses
  has_and_belongs_to_many :sections
end

app/models/tesda_course.rb
class TesdaCourse < ApplicationRecord
  belongs_to :tesda_course_sector
  has_and_belongs_to_many :teachers
  has_and_belongs_to_many :institutions
end

app/models/tesda_course_sector.rb
class TesdaCourseSector < ApplicationRecord
  has_many :tesda_courses, dependent: :delete_all
end

app/models/tuition.rb
class Tuition < ApplicationRecord
  belongs_to :institution
end

app/controllers/institutions_controller.rb
class InstitutionsController < SuperuserController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :inst_class, :address_province, :address_municipality, :address_street_no, :cong_distr_num, :region_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_records_helper.rb
module DataRecordsHelper
end

app/helpers/inst_contacts_helper.rb
module InstContactsHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tuitions_helper.rb
module TuitionsHelper
end

app/views/institutions/_form.html.erb
<%= form_with(model: institution, local: true) do |form| %>
  <% if institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.collection_select :region_id, Region.all, :id, :region_name, prompt: true %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :institution_name %>
  </div>

  <div class="field">
    <%= form.label :inst_class %>
    <%= form.text_field :inst_class, id: :institution_inst_class %>
  </div>

  <div class="field">
    <%= form.label :address_province %>
    <%= form.text_field :address_province, id: :institution_address_province %>
  </div>

  <div class="field">
    <%= form.label :address_municipality %>
    <%= form.text_field :address_municipality, id: :institution_address_municipality %>
  </div>

  <div class="field">
    <%= form.label :address_street_no %>
    <%= form.text_field :address_street_no, id: :institution_address_street_no %>
  </div>

  <div class="field">
    <%= form.label :cong_distr_num %>
    <%= form.text_field :cong_distr_num, id: :institution_cong_distr_num %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Institutions</h1>

<table class = "table-bordered stats-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Classification</th>
      <th>Province</th>
      <th>Municipality</th>
      <th>Street address</th>
      <th>Congressional district number</th>
      <% if admin_signed_in? %>
        <th colspan="3"></th>
      <% else %>
        <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.name %></td>
        <td><%= institution.inst_class %></td>
        <td><%= institution.address_province %></td>
        <td><%= institution.address_municipality %></td>
        <td><%= institution.address_street_no %></td>
        <td><%= institution.cong_distr_num %></td>
        <td><%= link_to 'Show', institution %></td>
      <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin_signed_in? %>
<%= link_to 'New Institution', new_institution_path %>
<% end %>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Institution: <%= @institution.name %></h2>

</br>
<h3> Institution summary</h3>

<div class = "container">
<table class = "table-bordered info-table">
  <tbody>
    <tr>
      <th>Classification</th>
      <td><%= @institution.inst_class %></td>
    </tr>
    <tr>
      <th>Province</th>
      <td><%= @institution.address_province %></td>
    </tr>
    <tr>
      <th>Municipality</th>
      <td><%= @institution.address_municipality %></td>
    </tr>
    <tr>
      <th>Street address</th>
      <td><%= @institution.address_street_no %></td>
    </tr>
    <tr>
      <th>Congressional district number</th>
      <td><%= @institution.cong_distr_num%></td>
    </tr>
  </tbody>
</table>

</div>

<%= link_to 'Contacts', [@institution, :inst_contacts] %> |
<%= link_to 'Data Records', [@institution, :data_records] %> |
<%= link_to 'Tuitions', [@institution, :tuitions] %> |
<%= link_to 'Faculty Headcounts', [@institution, :faculty_headcounts] %>

</br>
</br>

<% if admin_signed_in? %>
<%= link_to 'Edit Institution', edit_institution_path(@institution) %> |
<% end %>
<%= link_to 'Back', institutions_path %>