config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :institutions do
    resources :data_records, :tuitions, :faculty_headcounts, :inst_contacts
  end
  resources :regions do
    resources :regional_data_records
  end
  devise_for :principals, :controllers => { registrations: 'registrations' }
  root to: 'institutions#index'
  resources :sections
  resources :teachers
  resources :tesda_courses
  resources :tesda_course_sectors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_record.rb
class DataRecord < ApplicationRecord
  belongs_to :institution
end

app/models/faculty_headcount.rb
class FacultyHeadcount < ApplicationRecord
  belongs_to :institution
end

app/models/inst_contact.rb
class InstContact < ApplicationRecord
  belongs_to :institution
end

app/models/institution.rb
class Institution < ApplicationRecord
  belongs_to :region
  has_many :data_records, dependent: :delete_all
  has_many :faculty_headcounts, dependent: :delete_all
  has_many :tuitions, dependent: :delete_all
  has_many :inst_contacts, dependent: :delete_all
  has_and_belongs_to_many :tesda_courses
  has_many :sections, dependent: :delete_all
  has_many :teachers, dependent: :delete_all
  has_many :principals, dependent: :delete_all
end

app/models/principal.rb
class Principal < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :institution
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :regional_data_records, dependent: :delete_all
  has_many :institutions, dependent: :delete_all
end

app/models/regional_data_record.rb
class RegionalDataRecord < ApplicationRecord
  belongs_to :region
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :institution
  has_and_belongs_to_many :teachers
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :institution
  has_and_belongs_to_many :tesda_courses
  has_and_belongs_to_many :sections
end

app/models/tesda_course.rb
class TesdaCourse < ApplicationRecord
  belongs_to :tesda_course_sector
  has_and_belongs_to_many :teachers
  has_and_belongs_to_many :institutions
end

app/models/tesda_course_sector.rb
class TesdaCourseSector < ApplicationRecord
  has_many :tesda_courses, dependent: :delete_all
end

app/models/tuition.rb
class Tuition < ApplicationRecord
  belongs_to :institution
end

app/controllers/regional_data_records_controller.rb
class RegionalDataRecordsController < SuperuserController
  before_action :set_region
  before_action :set_regional_data_record, only: [:show, :edit, :update, :destroy]

  # GET /regional_data_records
  # GET /regional_data_records.json
  def index
    @regional_data_records = @region.regional_data_records.all
  end

  # GET /regional_data_records/1
  # GET /regional_data_records/1.json
  def show
  end

  # GET /regional_data_records/new
  def new
    @regional_data_record = @region.regional_data_records.new
  end

  # GET /regional_data_records/1/edit
  def edit
  end

  # POST /regional_data_records
  # POST /regional_data_records.json
  def create
    @regional_data_record = @region.regional_data_records.new(regional_data_record_params)

    respond_to do |format|
      if @regional_data_record.save
        format.html { redirect_to [@region, @regional_data_record], notice: 'Regional data record was successfully created.' }
        format.json { render :show, status: :created, location: @regional_data_record }
      else
        format.html { render :new }
        format.json { render json: @regional_data_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regional_data_records/1
  # PATCH/PUT /regional_data_records/1.json
  def update
    respond_to do |format|
      if @regional_data_record.update(regional_data_record_params)
        format.html { redirect_to [@region, @regional_data_record], notice: 'Regional data record was successfully updated.' }
        format.json { render :show, status: :ok, location: @regional_data_record }
      else
        format.html { render :edit }
        format.json { render json: @regional_data_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regional_data_records/1
  # DELETE /regional_data_records/1.json
  def destroy
    @regional_data_record.destroy
    respond_to do |format|
      format.html { redirect_to region_regional_data_records_url, notice: 'Regional data record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:region_id])
    end
    def set_regional_data_record
      @regional_data_record = RegionalDataRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regional_data_record_params
      params.require(:regional_data_record).permit(:region_id, :release_date, :acadyr, :cost_per_stud, :private_nonsec, :private_sec, :special_HEI, :other_govt_schools, :ched_supervised_institution, :local_colleges_and_uni, :SUCs_main, :SUCs_sat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_records_helper.rb
module DataRecordsHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/regional_data_records_helper.rb
module RegionalDataRecordsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tuitions_helper.rb
module TuitionsHelper
end

app/views/regional_data_records/_form.html.erb
<%= form_for([@region, regional_data_record], local: true) do |form| %>
  <% if regional_data_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(regional_data_record.errors.count, "error") %> prohibited this regional_data_record from being saved:</h2>

      <ul>
      <% regional_data_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :region_id %>
    <%= form.text_field :region_id, id: :regional_data_record_region_id %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date, id: :regional_data_record_release_date %>
  </div>

  <div class="field">
    <%= form.label :acadyr %>
    <%= form.number_field :acadyr, id: :regional_data_record_acadyr %>
  </div>

  <div class="field">
    <%= form.label :cost_per_stud %>
    <%= form.text_field :cost_per_stud, id: :regional_data_record_cost_per_stud %>
  </div>

  <div class="field">
    <%= form.label :private_nonsec %>
    <%= form.number_field :private_nonsec, id: :regional_data_record_private_nonsec %>
  </div>

  <div class="field">
    <%= form.label :private_sec %>
    <%= form.number_field :private_sec, id: :regional_data_record_private_sec %>
  </div>

  <div class="field">
    <%= form.label :special_HEI %>
    <%= form.number_field :special_HEI, id: :regional_data_record_special_HEI %>
  </div>

  <div class="field">
    <%= form.label :other_govt_schools %>
    <%= form.number_field :other_govt_schools, id: :regional_data_record_other_govt_schools %>
  </div>

  <div class="field">
    <%= form.label :ched_supervised_institution %>
    <%= form.number_field :ched_supervised_institution, id: :regional_data_record_ched_supervised_institution %>
  </div>

  <div class="field">
    <%= form.label :local_colleges_and_uni %>
    <%= form.number_field :local_colleges_and_uni, id: :regional_data_record_local_colleges_and_uni %>
  </div>

  <div class="field">
    <%= form.label :SUCs_main %>
    <%= form.text_field :SUCs_main, id: :regional_data_record_SUCs_main %>
  </div>

  <div class="field">
    <%= form.label :SUCs_sat %>
    <%= form.number_field :SUCs_sat, id: :regional_data_record_SUCs_sat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/regional_data_records/edit.html.erb
<h1>Editing Regional Data Record</h1>

<%= render 'form', regional_data_record: @regional_data_record %>

<%= link_to 'Show', [@region, @regional_data_record] %> |
<%= link_to 'Back', region_regional_data_records_path %>

app/views/regional_data_records/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Region: <%= @region.region_name %></h2>

</br>

<h3>Regional Data Records</h3>
<table class = "table-bordered stats-table">
  <thead>
    <tr>
      <th>Release date</th>
      <th>Academic year and term</th>
      <th>Cost per student</th>
      <th>Private nonsec</th>
      <th>Private sec</th>
      <th>Special HEIs</th>
      <th>Other government schools</th>
      <th>CHED-supervised institutions</th>
      <th>Local colleges and universities</th>
      <th>SUCs main</th>
      <th>SUCs sat</th>
      <% if admin_signed_in? %>
        <th colspan="3"></th>
      <% else %>
        <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @regional_data_records.each do |regional_data_record| %>
      <tr>
        <td><%= regional_data_record.release_date %></td>
        <td><%= regional_data_record.acadyr %></td>
        <td><%= regional_data_record.cost_per_stud %></td>
        <td><%= regional_data_record.private_nonsec %></td>
        <td><%= regional_data_record.private_sec %></td>
        <td><%= regional_data_record.special_HEI %></td>
        <td><%= regional_data_record.other_govt_schools %></td>
        <td><%= regional_data_record.ched_supervised_institution %></td>
        <td><%= regional_data_record.local_colleges_and_uni %></td>
        <td><%= regional_data_record.SUCs_main %></td>
        <td><%= regional_data_record.SUCs_sat %></td>
        <td><%= link_to 'Show', [@region, regional_data_record] %></td>
      <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_region_regional_data_record_path(@region, regional_data_record) %></td>
        <td><%= link_to 'Destroy', [@region, regional_data_record], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin_signed_in? %>
<%= link_to 'New Regional Data Record', new_region_regional_data_record_path %> |
<% end %>
<%= link_to 'Back', @region %>

app/views/regional_data_records/new.html.erb
<h1>New Regional Data Record</h1>

<%= render 'form', regional_data_record: @regional_data_record %>

<%= link_to 'Back', region_regional_data_records_path %>

app/views/regional_data_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Region:</strong>
  <%= @regional_data_record.region.region_name %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @regional_data_record.release_date %>
</p>

<p>
  <strong>Acadyr:</strong>
  <%= @regional_data_record.acadyr %>
</p>

<p>
  <strong>Cost per stud:</strong>
  <%= @regional_data_record.cost_per_stud %>
</p>

<p>
  <strong>Private nonsec:</strong>
  <%= @regional_data_record.private_nonsec %>
</p>

<p>
  <strong>Private sec:</strong>
  <%= @regional_data_record.private_sec %>
</p>

<p>
  <strong>Special hei:</strong>
  <%= @regional_data_record.special_HEI %>
</p>

<p>
  <strong>Other govt schools:</strong>
  <%= @regional_data_record.other_govt_schools %>
</p>

<p>
  <strong>Ched supervised institution:</strong>
  <%= @regional_data_record.ched_supervised_institution %>
</p>

<p>
  <strong>Local colleges and uni:</strong>
  <%= @regional_data_record.local_colleges_and_uni %>
</p>

<p>
  <strong>Sucs main:</strong>
  <%= @regional_data_record.SUCs_main %>
</p>

<p>
  <strong>Sucs sat:</strong>
  <%= @regional_data_record.SUCs_sat %>
</p>

<% if admin_signed_in? %>
<%= link_to 'Edit', edit_region_regional_data_record_path(@region, @regional_data_record) %> |
<% end %>
<%= link_to 'Back', region_regional_data_records_path %>