config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :institutions do
    resources :data_records, :tuitions, :faculty_headcounts, :inst_contacts
  end
  resources :regions do
    resources :regional_data_records
  end
  devise_for :principals, :controllers => { registrations: 'registrations' }
  root to: 'institutions#index'
  resources :sections
  resources :teachers
  resources :tesda_courses
  resources :tesda_course_sectors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_record.rb
class DataRecord < ApplicationRecord
  belongs_to :institution
end

app/models/faculty_headcount.rb
class FacultyHeadcount < ApplicationRecord
  belongs_to :institution
end

app/models/inst_contact.rb
class InstContact < ApplicationRecord
  belongs_to :institution
end

app/models/institution.rb
class Institution < ApplicationRecord
  belongs_to :region
  has_many :data_records, dependent: :delete_all
  has_many :faculty_headcounts, dependent: :delete_all
  has_many :tuitions, dependent: :delete_all
  has_many :inst_contacts, dependent: :delete_all
  has_and_belongs_to_many :tesda_courses
  has_many :sections, dependent: :delete_all
  has_many :teachers, dependent: :delete_all
  has_many :principals, dependent: :delete_all
end

app/models/principal.rb
class Principal < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :institution
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :regional_data_records, dependent: :delete_all
  has_many :institutions, dependent: :delete_all
end

app/models/regional_data_record.rb
class RegionalDataRecord < ApplicationRecord
  belongs_to :region
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :institution
  has_and_belongs_to_many :teachers
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :institution
  has_and_belongs_to_many :tesda_courses
  has_and_belongs_to_many :sections
end

app/models/tesda_course.rb
class TesdaCourse < ApplicationRecord
  belongs_to :tesda_course_sector
  has_and_belongs_to_many :teachers
  has_and_belongs_to_many :institutions
end

app/models/tesda_course_sector.rb
class TesdaCourseSector < ApplicationRecord
  has_many :tesda_courses, dependent: :delete_all
end

app/models/tuition.rb
class Tuition < ApplicationRecord
  belongs_to :institution
end

app/controllers/tesda_course_sectors_controller.rb
class TesdaCourseSectorsController < SuperuserController
  before_action :set_tesda_course_sector, only: [:show, :edit, :update, :destroy]

  # GET /tesda_course_sectors
  # GET /tesda_course_sectors.json
  def index
    @tesda_course_sectors = TesdaCourseSector.all
  end

  # GET /tesda_course_sectors/1
  # GET /tesda_course_sectors/1.json
  def show
    @tesda_courses = @tesda_course_sector.tesda_courses
  end

  # GET /tesda_course_sectors/new
  def new
    @tesda_course_sector = TesdaCourseSector.new
  end

  # GET /tesda_course_sectors/1/edit
  def edit
  end

  # POST /tesda_course_sectors
  # POST /tesda_course_sectors.json
  def create
    @tesda_course_sector = TesdaCourseSector.new(tesda_course_sector_params)

    respond_to do |format|
      if @tesda_course_sector.save
        format.html { redirect_to @tesda_course_sector, notice: 'Tesda course sector was successfully created.' }
        format.json { render :show, status: :created, location: @tesda_course_sector }
      else
        format.html { render :new }
        format.json { render json: @tesda_course_sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tesda_course_sectors/1
  # PATCH/PUT /tesda_course_sectors/1.json
  def update
    respond_to do |format|
      if @tesda_course_sector.update(tesda_course_sector_params)
        format.html { redirect_to @tesda_course_sector, notice: 'Tesda course sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @tesda_course_sector }
      else
        format.html { render :edit }
        format.json { render json: @tesda_course_sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tesda_course_sectors/1
  # DELETE /tesda_course_sectors/1.json
  def destroy
    @tesda_course_sector.destroy
    respond_to do |format|
      format.html { redirect_to tesda_course_sectors_url, notice: 'Tesda course sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tesda_course_sector
      @tesda_course_sector = TesdaCourseSector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tesda_course_sector_params
      params.require(:tesda_course_sector).permit(:tcs_name, :tcs_desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_records_helper.rb
module DataRecordsHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tesda_course_sectors_helper.rb
module TesdaCourseSectorsHelper
end

app/helpers/tuitions_helper.rb
module TuitionsHelper
end

app/views/tesda_course_sectors/_form.html.erb
<%= form_with(model: tesda_course_sector, local: true) do |form| %>
  <% if tesda_course_sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tesda_course_sector.errors.count, "error") %> prohibited this tesda_course_sector from being saved:</h2>

      <ul>
      <% tesda_course_sector.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tcs_name %>
    <%= form.text_field :tcs_name, id: :tesda_course_sector_tcs_name %>
  </div>

  <div class="field">
    <%= form.label :tcs_desc %>
    <%= form.text_field :tcs_desc, id: :tesda_course_sector_tcs_desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tesda_course_sectors/edit.html.erb
<h1>Editing Tesda Course Sector</h1>

<%= render 'form', tesda_course_sector: @tesda_course_sector %>

<%= link_to 'Show', @tesda_course_sector %> |
<%= link_to 'Back', tesda_course_sectors_path %>

app/views/tesda_course_sectors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>TESDA Course Sectors</h1>

<table class = "table-bordered stats-table">
  <thead>
    <tr>
      <th>Sector name</th>
      <th>Sector description</th>
      <% if admin_signed_in? %>
        <th colspan="3"></th>
      <% else %>
        <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @tesda_course_sectors.each do |tesda_course_sector| %>
      <tr>
        <td><%= tesda_course_sector.tcs_name %></td>
        <td><%= tesda_course_sector.tcs_desc %></td>
        <td><%= link_to 'Show', tesda_course_sector %></td>
      <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_tesda_course_sector_path(tesda_course_sector) %></td>
        <td><%= link_to 'Destroy', tesda_course_sector, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin_signed_in? %>
<%= link_to 'New TESDA Course Sector', new_tesda_course_sector_path %>
<% end %>

app/views/tesda_course_sectors/new.html.erb
<h1>New Tesda Course Sector</h1>

<%= render 'form', tesda_course_sector: @tesda_course_sector %>

<%= link_to 'Back', tesda_course_sectors_path %>

app/views/tesda_course_sectors/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  TESDA Course Sector: <%= @tesda_course_sector.tcs_name %>
</h2>

</br>

<h3> Sector summary </h3>

<table class = "table-bordered info-table">
  <tr>
    <th>Course Sector Description</th>
    <td><%= @tesda_course_sector.tcs_desc %></td>
  </tr>
</table>

</br>

<h3>TESDA Courses under <%= @tesda_course_sector.tcs_name %></h3>

<table class = "table-bordered stats-table">
  <thead>
    <tr>
      <th>Course Name</th>
      <th>Duration in hours</th>
      <% if admin_signed_in? %>
        <th colspan="3"></th>
      <% else %>
        <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @tesda_courses.each do |tesda_course| %>
      <tr>
        <td><%= tesda_course.tc_name %></td>
        <td><%= tesda_course.tc_hrs_dur %></td>
        <td><%= link_to 'Show course', tesda_course %></td>
      <% if admin_signed_in? %>
        <td><%= link_to 'Edit course', edit_tesda_course_path(tesda_course) %></td>
        <td><%= link_to 'Destroy course', tesda_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

</br>

<% if admin_signed_in? %>
<%= link_to 'New TESDA Course', new_tesda_course_path %> |
<%= link_to 'Edit course sector', edit_tesda_course_sector_path(@tesda_course_sector) %> |
<% end %>
<%= link_to 'Back', tesda_course_sectors_path %>