config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :institutions do
    resources :data_records, :tuitions, :faculty_headcounts, :inst_contacts
  end
  resources :regions do
    resources :regional_data_records
  end
  devise_for :principals, :controllers => { registrations: 'registrations' }
  root to: 'institutions#index'
  resources :sections
  resources :teachers
  resources :tesda_courses
  resources :tesda_course_sectors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_record.rb
class DataRecord < ApplicationRecord
  belongs_to :institution
end

app/models/faculty_headcount.rb
class FacultyHeadcount < ApplicationRecord
  belongs_to :institution
end

app/models/inst_contact.rb
class InstContact < ApplicationRecord
  belongs_to :institution
end

app/models/institution.rb
class Institution < ApplicationRecord
  belongs_to :region
  has_many :data_records, dependent: :delete_all
  has_many :faculty_headcounts, dependent: :delete_all
  has_many :tuitions, dependent: :delete_all
  has_many :inst_contacts, dependent: :delete_all
  has_and_belongs_to_many :tesda_courses
  has_many :sections, dependent: :delete_all
  has_many :teachers, dependent: :delete_all
  has_many :principals, dependent: :delete_all
end

app/models/principal.rb
class Principal < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :institution
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :regional_data_records, dependent: :delete_all
  has_many :institutions, dependent: :delete_all
end

app/models/regional_data_record.rb
class RegionalDataRecord < ApplicationRecord
  belongs_to :region
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :institution
  has_and_belongs_to_many :teachers
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :institution
  has_and_belongs_to_many :tesda_courses
  has_and_belongs_to_many :sections
end

app/models/tesda_course.rb
class TesdaCourse < ApplicationRecord
  belongs_to :tesda_course_sector
  has_and_belongs_to_many :teachers
  has_and_belongs_to_many :institutions
end

app/models/tesda_course_sector.rb
class TesdaCourseSector < ApplicationRecord
  has_many :tesda_courses, dependent: :delete_all
end

app/models/tuition.rb
class Tuition < ApplicationRecord
  belongs_to :institution
end

app/controllers/data_records_controller.rb
class DataRecordsController < SuperuserController
  before_action :set_institution
  before_action :set_data_record, only: [:show, :edit, :update, :destroy]

  # GET /data_records
  # GET /data_records.json
  def index
    @data_records = @institution.data_records.all
  end

  # GET /data_records/1
  # GET /data_records/1.json
  def show
  end

  # GET /data_records/new
  def new
    @data_record = @institution.data_records.new
  end

  # GET /data_records/1/edit
  def edit
  end

  # POST /data_records
  # POST /data_records.json
  def create
    @data_record = @institution.data_records.new(data_record_params)

    respond_to do |format|
      if @data_record.save
        format.html { redirect_to [@institution, @data_record], notice: 'Data record was successfully created.' }
        format.json { render :show, status: :created, location: @data_record }
      else
        format.html { render :new }
        format.json { render json: @data_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_records/1
  # PATCH/PUT /data_records/1.json
  def update
    respond_to do |format|
      if @data_record.update(data_record_params)
        format.html { redirect_to [@institution, @data_record], notice: 'Data record was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_record }
      else
        format.html { render :edit }
        format.json { render json: @data_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_records/1
  # DELETE /data_records/1.json
  def destroy
    @data_record.destroy
    respond_to do |format|
      format.html { redirect_to [@institution, :data_records], notice: 'Data record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:institution_id])
    end
    def set_data_record
      @data_record = DataRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_record_params
      params.require(:data_record).permit(:institution_id, :release_date, :acadyr_termno, :stud_count, :enrolled, :graduated, :cost_per_stud)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_records_helper.rb
module DataRecordsHelper
end

app/helpers/inst_contacts_helper.rb
module InstContactsHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tuitions_helper.rb
module TuitionsHelper
end

app/views/data_records/_form.html.erb
<%= form_for([@institution, data_record], local: true) do |form| %>
  <% if data_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_record.errors.count, "error") %> prohibited this data_record from being saved:</h2>

      <ul>
      <% data_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :institution_id %>
    <%= form.text_field :institution_id, id: :data_record_institution_id %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date, id: :data_record_release_date %>
  </div>

  <div class="field">
    <%= form.label :acadyr_termno %>
    <%= form.text_field :acadyr_termno, id: :data_record_acadyr_termno %>
  </div>

  <div class="field">
    <%= form.label :stud_count %>
    <%= form.text_field :stud_count, id: :data_record_stud_count %>
  </div>

  <div class="field">
    <%= form.label :enrolled %>
    <%= form.text_field :enrolled, id: :data_record_enrolled %>
  </div>

  <div class="field">
    <%= form.label :graduated %>
    <%= form.text_field :graduated, id: :data_record_graduated %>
  </div>

  <div class="field">
    <%= form.label :cost_per_stud %>
    <%= form.text_field :cost_per_stud, id: :data_record_cost_per_stud %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/data_records/edit.html.erb
<h1>Editing Data Record</h1>

<%= render 'form', data_record: @data_record %>

<%= link_to 'Show', [@institution, @data_record] %> |
<%= link_to 'Back', institution_data_records_path %>

app/views/data_records/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Institution: <%= @institution.name %></h2>
<h3> Data Records</h3>

<table class = "table-bordered stats-table">
  <thead>
    <tr>
      <th>Release date</th>
      <th>Academic year and term</th>
      <th>Student count</th>
      <th>Number enrolled</th>
      <th>Number graduated</th>
      <th>Cost per student</th>
      <% if admin_signed_in? %>
        <th colspan="3"></th>
      <% else %>
        <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @data_records.each do |data_record| %>
      <tr>
        <td><%= data_record.release_date %></td>
        <td><%= data_record.acadyr_termno %></td>
        <td><%= data_record.stud_count %></td>
        <td><%= data_record.enrolled %></td>
        <td><%= data_record.graduated %></td>
        <td><%= data_record.cost_per_stud %></td>
        <td><%= link_to 'Show', [@institution, data_record] %></td>
      <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_institution_data_record_path(@institution, data_record) %></td>
        <td><%= link_to 'Destroy', [@institution, data_record], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin_signed_in? %>
<%= link_to 'New Data Record', new_institution_data_record_path %> |
<% end %>
<%= link_to 'Back', @institution %>

app/views/data_records/new.html.erb
<h1>New Data Record</h1>

<%= render 'form', data_record: @data_record %>

<%= link_to 'Back', institution_data_records_path %>

app/views/data_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Institution:</strong>
  <%= @data_record.institution.name %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @data_record.release_date %>
</p>

<p>
  <strong>Acadyr termno:</strong>
  <%= @data_record.acadyr_termno %>
</p>

<p>
  <strong>Stud count:</strong>
  <%= @data_record.stud_count %>
</p>

<p>
  <strong>Enrolled:</strong>
  <%= @data_record.enrolled %>
</p>

<p>
  <strong>Graduated:</strong>
  <%= @data_record.graduated %>
</p>

<p>
  <strong>Cost per stud:</strong>
  <%= @data_record.cost_per_stud %>
</p>

<% if admin_signed_in? %>
<%= link_to 'Edit', edit_institution_data_record_path(@institution, @data_record) %> |
<% end %>
<%= link_to 'Back', institution_data_records_path %>